spring:
  sql:
    init:
      mode: always

  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: jdbc:h2:file:~\dbs\api\db
    username: sa
    password: sa
    classpath: data.sql
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true


logging:
  level:
    org:
      hibernate:
        SQL: DEBUG'
        type:
          descriptor:
            sql:
              BaseBinder: TRACE

#auth0:
#  audience: BigBookSwap
#  issuer: https://localhost:8080/api/v1
#
